-- Run this in your Supabase SQL Editor to create the required table

-- 1. Create the table
CREATE TABLE IF NOT EXISTS accesook (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    username text NOT NULL UNIQUE,
    password text NOT NULL,
    user_metadata jsonb DEFAULT '{}'::jsonb
);

-- 2. Enable RLS
ALTER TABLE accesook ENABLE ROW LEVEL SECURITY;

-- 3. Create policy for public access (since we use custom auth)
DROP POLICY IF EXISTS "Allow public access to accesook" ON accesook;

CREATE POLICY "Allow public access to accesook"
ON accesook
FOR ALL
USING (true)
WITH CHECK (true);

-- 4. Grant permissions
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;

-- 5. Insert default admin user (optional, code does this too but good to have)
INSERT INTO accesook (username, password, user_metadata)
VALUES (
    'admin',
    '123',
    '{
        "id": "u1",
        "role": "admin",
        "fullName": "Super Admin",
        "avatarUrl": "https://i.pravatar.cc/150?u=admin",
        "allowedFolders": [{"pathPrefix": "/", "permissions": ["read", "write", "delete", "download"]}],
        "sharedFiles": []
    }'::jsonb
) ON CONFLICT (username) DO NOTHING;

-- 6. Create notifications table
CREATE TABLE IF NOT EXISTS notifications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    type text NOT NULL,
    message text NOT NULL,
    actor_username text NOT NULL,
    is_read boolean DEFAULT false
);

-- 7. Enable RLS for notifications
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;

-- 8. Create policy for notifications
DROP POLICY IF EXISTS "Allow public access to notifications" ON notifications;

CREATE POLICY "Allow public access to notifications"
ON notifications
FOR ALL
USING (true)
WITH CHECK (true);

-- 9. Grant permissions for notifications
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;
